// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbGQnq0peFGmrEiXzZ9Mu_csZMhfYvuvQ',
    appId: '1:295950725032:web:54c62bb7adfdb40e9f779d',
    messagingSenderId: '295950725032',
    projectId: 'smart-trash-bin-984a8',
    authDomain: 'smart-trash-bin-984a8.firebaseapp.com',
    databaseURL: 'https://smart-trash-bin-984a8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-trash-bin-984a8.firebasestorage.app',
    measurementId: 'G-CKLZ4Y93TC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfBCZCYOltQEydgsgKK7P-MO8TmEX5LMY',
    appId: '1:295950725032:android:6d8c4f482fe17c969f779d',
    messagingSenderId: '295950725032',
    projectId: 'smart-trash-bin-984a8',
    databaseURL: 'https://smart-trash-bin-984a8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-trash-bin-984a8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNJ4BRd1R5nEzUrj1EoNyrb-_pszCaX2Q',
    appId: '1:295950725032:ios:208271f3a6cc95c59f779d',
    messagingSenderId: '295950725032',
    projectId: 'smart-trash-bin-984a8',
    databaseURL: 'https://smart-trash-bin-984a8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-trash-bin-984a8.firebasestorage.app',
    iosBundleId: 'com.example.smartTrashBinApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNJ4BRd1R5nEzUrj1EoNyrb-_pszCaX2Q',
    appId: '1:295950725032:ios:208271f3a6cc95c59f779d',
    messagingSenderId: '295950725032',
    projectId: 'smart-trash-bin-984a8',
    databaseURL: 'https://smart-trash-bin-984a8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-trash-bin-984a8.firebasestorage.app',
    iosBundleId: 'com.example.smartTrashBinApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbGQnq0peFGmrEiXzZ9Mu_csZMhfYvuvQ',
    appId: '1:295950725032:web:4605778e3714619e9f779d',
    messagingSenderId: '295950725032',
    projectId: 'smart-trash-bin-984a8',
    authDomain: 'smart-trash-bin-984a8.firebaseapp.com',
    databaseURL: 'https://smart-trash-bin-984a8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-trash-bin-984a8.firebasestorage.app',
    measurementId: 'G-9JG31G5W22',
  );
}
